### ISSUE TITLE
New Idea: Splitting website to dedicated repository

### ISSUE THREAD

**Issue by SoulRepo** [cryptocheems/cheemscoin#11]
**Is your feature request related to a problem? Please describe.**
No, but it would help with code management. It would also allow the shrinking of the size of the repository, however it's less than a megabyte so that might not matter.

**Describe the solution you'd like**
A simple fork of the website code to another repository under the same organization.

**Describe alternatives you've considered**
Keeping it wouldn't change much for a while, but maybe this could be started when all current stuff being worked on is done.

**Potential applications to use for idea**
This doesn't need any third-party applications, as it's just managing the code.

**Additional context**
None needed.

- [X] By checking this, you have read the Contributing Guidelines page.

**Comment by SoulRepo** [comment]
Probably the biggest problem is making sure it works without breaking.

**Comment by kowasaur** [comment]
The problem is that the website needs the artifacts generated by the smart contracts. I guess we could just copy the artifacts over when we need them but I feel like having it all in one place is easier
