### ISSUE TITLE
Add a donation page

### ISSUE THREAD

**Issue by soulthunk** [cryptocheems/cheemscoin#15]
**Please describe what the idea is**
A simple donation page with a few wallet addresses people can give cryptocurrency to, like Cheemscoin itself or Ethereum.

**Please describe some ideas on how you would implement this**
Create a TypeScript page that just shows the wallet addresses and a reason you should donate.

**Additional context**
None.

- [X] By checking this, you have read the Contributing Guidelines page.

**Comment by SoulRepo** [comment]
I plan to do this once most of my school stuff is done.

**Comment by kowasaur** [comment]
Im not so sure about this now cause I think it looks kinda bad. We already have a large amount of Cheemscoin so we really don't need donations. I'll make a poll on the server anyways to see what people think

**Comment by soulthunk** [comment]
please delete
