### ISSUE TITLE
Implement custom 404 page

### ISSUE THREAD

**Issue by SoulRepo** [cryptocheems/cheemscoin#6]
This is a page to discuss the implementation of creating a 404 page for the website.

**Comment by SoulRepo** [comment]
I plan to start building this soon, as soon as I get my new keyboard.

**Comment by kowasaur** [comment]
nice

**Comment by SoulRepo** [comment]
Alright, I have my new keyboard. I will start soon.

**Comment by SoulRepo** [comment]
I added some text, should almost be ready.
